version: '3'

services:
  redis-cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  cepservice:
    image: edjdc/cepservice
    ports:
      - "9000:8080"
    restart: always
    depends_on:
      - redis-cache
    environment:
      spring.redis.host: redis-cache
      spring.redis.port: 6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3